### PR TITLE
Eng 256 add metadata

### PR DESCRIPTION
**Pull request by tsharkey**
Adds:
- a new http problem type with metadata. the metadata will be used to be able to pass other things along to callers like error information from facebook when trying to activate a new campaign
- a new function to get a specific field from the data errors fields

### CODE REVIEW

**Review by sprak3000 — APPROVED** [review]
👍🏽 👋🏽

**Comment by tsharkey** [comment]
@sprak3000 I noticed this wasn't a private repo haha

**Comment by sloiselle** [comment]
Nope. Definitely not private 😉

**Comment by tsharkey** [comment]
haha, you also can't set these repos to private because they are forked from the healthimation one. I am gonna blame @divideandconquer for this one

**Review by sean-m-slattery — APPROVED** [review]

**Pull request merged**
